// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"

	"github.com/google/uuid"
)

type Athlete struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Exercise struct {
	ID           uuid.UUID `json:"id"`
	Wpid         uuid.UUID `json:"wpid"`
	Aid          uuid.UUID `json:"aid"`
	Name         string    `json:"name"`
	TargetRep    int32     `json:"target_rep"`
	NumSets      int32     `json:"num_sets"`
	Weight       float64   `json:"weight"`
	RestDuration float64   `json:"rest_duration"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type WorkoutPlan struct {
	ID        uuid.UUID `json:"id"`
	Aid       uuid.UUID `json:"aid"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
