// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Auth struct {
	Token string `json:"token"`
}

type Eset struct {
	ID               string      `json:"id"`
	Eid              string      `json:"eid"`
	User             *PublicUser `json:"user"`
	ActualRepCount   int         `json:"actualRepCount"`
	Duration         float64     `json:"duration"`
	RestTimeDuration float64     `json:"restTimeDuration"`
	CreatedAt        time.Time   `json:"createdAt"`
	UpdatedAt        time.Time   `json:"updatedAt"`
}

type EsetUpdate struct {
	ID               string  `json:"id"`
	ActualRepCount   int     `json:"actualRepCount"`
	Duration         float64 `json:"duration"`
	RestTimeDuration float64 `json:"restTimeDuration"`
}

type Exercise struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Wid       string      `json:"wid"`
	User      *PublicUser `json:"user"`
	Weight    float64     `json:"weight"`
	TargetRep int         `json:"targetRep"`
	RestTime  float64     `json:"restTime"`
	NumSets   int         `json:"numSets"`
	CreatedAt time.Time   `json:"createdAt"`
	UpdatedAt time.Time   `json:"updatedAt"`
}

type ExerciseUpdate struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Weight    float64 `json:"weight"`
	TargetRep int     `json:"targetRep"`
	RestTime  float64 `json:"restTime"`
	NumSets   int     `json:"numSets"`
}

type Login struct {
	Username *string `json:"username"`
	Email    *string `json:"email"`
	Password string  `json:"password"`
}

type NewEset struct {
	Eid              string  `json:"eid"`
	ActualRepCount   int     `json:"actualRepCount"`
	Duration         float64 `json:"duration"`
	RestTimeDuration float64 `json:"restTimeDuration"`
}

type NewExercise struct {
	Wid  string `json:"wid"`
	Name string `json:"name"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Confirm  string `json:"confirm"`
}

type NewWorkout struct {
	Title string `json:"title"`
}

type PublicUser struct {
	Username string  `json:"username"`
	Weight   float64 `json:"weight"`
	Height   float64 `json:"height"`
	Gender   string  `json:"gender"`
}

type Workout struct {
	ID        string      `json:"id"`
	Title     string      `json:"title"`
	CreatedAt time.Time   `json:"createdAt"`
	UpdatedAt time.Time   `json:"updatedAt"`
	User      *PublicUser `json:"user"`
}

type WorkoutUpdate struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}
