// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Auth struct {
	Token string `json:"token"`
}

type Exercise struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Wid       string      `json:"wid"`
	User      *PublicUser `json:"user"`
	Weight    float64     `json:"weight"`
	TargetRep int         `json:"targetRep"`
	RestTime  float64     `json:"restTime"`
	NumSets   int         `json:"numSets"`
}

type ExerciseUpdate struct {
	Name      *string  `json:"name"`
	Weight    *float64 `json:"weight"`
	TargetRep *int     `json:"targetRep"`
	RestTime  *float64 `json:"restTime"`
	NumSets   *int     `json:"numSets"`
}

type Login struct {
	Username *string `json:"username"`
	Email    *string `json:"email"`
	Password string  `json:"password"`
}

type NewExercise struct {
	Wid  string `json:"wid"`
	Name string `json:"name"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Confirm  string `json:"confirm"`
}

type NewWorkout struct {
	Title string `json:"title"`
}

type PublicUser struct {
	Username string  `json:"username"`
	Weight   float64 `json:"weight"`
	Height   float64 `json:"height"`
	Gender   string  `json:"gender"`
}

type Workout struct {
	ID        string      `json:"id"`
	Title     string      `json:"title"`
	CreatedAt time.Time   `json:"createdAt"`
	UpdatedAt time.Time   `json:"updatedAt"`
	User      *PublicUser `json:"user"`
}

type WorkoutUpdate struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}
