CREATE TABLE users(
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(120) NOT NULL UNIQUE,
    email VARCHAR(256) NOT NULL UNIQUE, 
    hashed_password VARCHAR(256) NOT NULL,
    joined TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    weight DECIMAL DEFAULT 0.0,
    height DECIMAL DEFAULT 0.0,
    gender VARCHAR(7) NOT NULL DEFAULT 'N/A'
);
