name: Run Tests

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
    test: 
      runs-on: ubuntu-20.04

      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
          with:
            stable: "false"
            go-version: "1.16.2"

        - name: Run Go Test
          run: go test ./...    

